apiVersion: storage.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: metal-vcluster
  namespace: p-default
spec:
  displayName: "Metal vCluster"
  clusterRef:
    cluster: metal-cp
    namespace: vcluster-metal-vcluster
  template:
    helmRelease:
      chart:
        version: "0.33.1"
      values: |-
        privateNodes:
          enabled: true
          vpn:
            enabled: true
          autoNodes:
            - provider: metal3
              static:
                - name: bare-metal
                  quantity: 1
              properties:
                vcluster.com/os-image: ubuntu2404-20260307
                vcluster.com/ssh-keys: demo
