apiVersion: storage.loft.sh/v1
kind: NodeProvider
metadata:
  name: metal3
spec:
  displayName: "Metal3 Bare Metal Hosts"
  metal3:
    clusterRef:
      cluster: rack-mgmt
      namespace: default
    deploy:
      multus:
        enabled: false
      metal3:
        enabled: true
      dhcp:
        enabled: true
        helmValues: |
          networkAttachmentDefinition:
            vip: 192.168.100.4/24
            config: |
              {
                "cniVersion": "0.3.1",
                "type": "bridge",
                "bridge": "br0",
                "isDefaultGateway": false
              }
    nodeTypes:
      - name: vm
